blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/mkemalgokce/Sayar/wiki
    about: Check out the documentation for help and guides
  - name: Discussions
    url: https://github.com/mkemalgokce/Sayar/discussions
    about: Ask questions and discuss ideas with the community
