name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint:
    runs-on: macos-latest
    name: SwiftLint
    steps:
      - uses: actions/checkout@v4

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint
        run: swiftlint lint --strict

  format:
    runs-on: macos-latest
    name: SwiftFormat
    steps:
      - uses: actions/checkout@v4

      - name: Install SwiftFormat
        run: |
          brew install swiftformat

      - name: Check SwiftFormat
        run: |
          swiftformat --lint .

  test:
    runs-on: macos-latest
    name: Unit Tests
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_26.0.app

      - name: Install Tuist
        run: |
          brew install tuist
          tuist version

      - name: Install dependencies
        run: |
          tuist install

      - name: Setup Firebase config for tests
        env:
          FIREBASE_CONFIG_DEV: ${{ secrets.FIREBASE_CONFIG_DEV }}
        run: |
          mkdir -p App/Resources/Firebase
          echo "$FIREBASE_CONFIG_DEV" | base64 --decode > App/Resources/Firebase/GoogleService-Info-Dev.plist

      - name: Generate Tuist project
        run: |
          tuist generate

      - name: Build and Test
        run: |
          xcodebuild test \
            -workspace Sayar.xcworkspace \
            -scheme "Sayar-Workspace-Dev" \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro' \
            -configuration Dev \
            -enableCodeCoverage YES \
            build test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
