name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint:
    runs-on: macos-latest
    name: SwiftLint
    steps:
      - uses: actions/checkout@v4

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint
        run: swiftlint lint --strict

  format:
    runs-on: macos-latest
    name: SwiftFormat
    steps:
      - uses: actions/checkout@v4

      - name: Install SwiftFormat
        run: |
          brew install swiftformat

      - name: Check SwiftFormat
        run: |
          swiftformat --lint .

  test:
    runs-on: macos-latest
    name: Unit Tests
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_26.0.app

      - name: Install Tuist
        run: |
          brew install tuist
          tuist version

      - name: Install dependencies
        run: |
          tuist install

      - name: Generate Tuist project
        run: |
          tuist generate

      - name: Run tests
        run: |
          xcodebuild test \
            -workspace Sayar.xcworkspace \
            -scheme "Sayar Dev" \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro' \
            -configuration Dev \
            -enableCodeCoverage YES \
            -derivedDataPath DerivedData

      - name: Generate coverage report
        run: |
          xcrun llvm-cov export -format="lcov" \
            -instr-profile DerivedData/Build/ProfileData/*/Coverage.profdata \
            DerivedData/Build/Products/Dev-iphonesimulator/Sayar.app/Sayar \
            > coverage.lcov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.lcov
          flags: unittests
          name: codecov-sayar
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
